name: Build and Deploy Site
on:
  push:
    branches:
      - main
      - "releases/**"
jobs:
  build-dev:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Write environment variables
        run: |
          touch .env.local
          echo "REACT_APP_API_ENDPOINT=\"${{ vars.VITE_API_ENDPOINT }}\"" >> .env.local
      - name: Build
        run: yarn build
  build-stable:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Write environment variables
        run: |
          touch .env.local
          echo "REACT_APP_API_ENDPOINT=\"${{ vars.VITE_API_ENDPOINT }}\"" >> .env.local
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
permissions:
  contents: write
